name: 'ImageMagick GHA'
description: 'GitHub Action wrapper for ImageMagick for file conversion and/or manipulation'

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: image
  color: black

##
#
inputs:
  source_directory:
    description: 'Directory passed to `find` for finding files'
    required: true

  find_regex:
    description: 'Regular Expression passed to `find` to limit found files, example "*.png"'
    required: true

  find_regextype:
    description: 'Regular Expression type passed to `find` available values are; "emacs", "posix-awk", "posix-basic", "posix-egrep", or "posix-extended"'
    required: true
    default: 'emacs'

  exec_magick:
    description: 'Executable name, with optional path, to ImageMagick executable'
    required: true
    default: 'magick'

  destination_extensions:
    description: 'Comma separated list of file extensions parsed and passed to `magick`, example "jpeg,avif"'
    required: true

  magick_opts:
    description: 'Additional parameters to pass to `magick` for each found file and destination extension'
    required: false

  destination_name_prefix:
    description: 'Optional prefix for output file names'
    required: false

  destination_name_suffix:
    description: 'Optional suffix for output file names'
    required: false

  destination_clobber:
    description: 'Enable clobbering preexisting files by setting to `1`'
    default: 0
    required: false

  verbose:
    description: 'Enable `printf` logging by setting non-zero integer value'
    default: 0
    required: false

##
#
outputs:
  found:
    description: 'New-line separated list of file paths found with `find` and provided inputs'

  wrote:
    description: 'New-line separated list of file paths written by `magick` with provided inputs'

  failed:
    description: 'New-line separated list of file paths `magick` failed to write'

